language: r

cache:
 - packages
 - apt: true
r: release
r_packages: devtools
r_github_packages: zappingseb/shinycandlestick

addons:
  apt:
    update: true
    packages:
      - libgdal1-dev
script:
- R CMD build .
- R CMD check *tar.gz