language: r

cache:
 - packages
 - apt: true
r: release
r_packages: devtools
addons:
  apt:
    update: true
    packages:
      - libgdal1-dev
      - libgdal1-1.7.0
script:
- R CMD build .
- R CMD check *tar.gz